name: Docs checks
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  pull_request:
    paths:
      - "docs/**"
      - ".github/actions/validate-docs-links/**"
      - ".github/actions/docs.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  validate-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Setup Node"
        uses: ./.github/actions/setup-node

      - name: "Build docs"
        run: |
          pnpm install --global vercel
          vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
          vercel build --token=${{ secrets.VERCEL_TOKEN }}
  validate-docs-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Setup Node"
        uses: ./.github/actions/setup-node

      - name: "Run link checker"
        run: cd docs && pnpm run check-links
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
